### ISSUE TITLE
안녕하세요 워터님의 피해자입니다.

### ISSUE THREAD

**Issue by sh9351** [dao7895/W.R.D#1]
안녕하세요. 저는 워터님의 피해자입니다.
워터님은 디스코드에서 사람들에게 뒷메로 서버를 홍보하셨습니다.
그러기에 저는 홍보를 하지 말라 화내지 않고 정확하게 "이런것좀 보내지 말아주세요 갠디로 홍보 보내지 말아주세요" 라고 말했습니다.
그러더니 워터님은 "오시면요" 라고 제가 안오면 계속 보내겠다는 듯이 협박을 하였습니다.
그래서 사과를 요구하자 말없이 저를 차단하셨고 저의 부계도 차단하셨습니다.
부디 워터님이 사과를 하셔 바른 사람이 되도록 도와주시면 감사하겠습니다.
도와주시는 방법은 단지 사과문을 올리실 때까지 외면해주시면 감사하겠습니다.
![image](https://user-images.githubusercontent.com/70079686/91515573-7177ea00-e924-11ea-9e4b-380c4f736fb1.png)

**Comment by wake3532** [comment]
ㄴㅇㄱ

**Comment by sh9351** [comment]
저기요 ㄴㅇㄱ가 뭡니까 사과하세요 저 끝까지 쫓아갑니다

2020년 9월 9일 (수) 오전 8:12, dao1234 <notifications@github.com>님이 작성:

**Comment by sh9351** [comment]
ㄴㅇㄱ가 뭡니까 사과하세요

**Comment by wake3532** [comment]
아 죄송합니다..

**Comment by sh9351** [comment]
ㄲㅇ
